name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    # 현재는 GitHub Actions기 제공해주는 ubuntu 러너를 사용합니다.
    runs-on: ubuntu-latest
    # 모든 도커 컨테이너는 이미지를 기반으로 합니다.
    # 컨테이너를 사용하기 위한 container 키를 지정합니다.
    # ubuntu 러너가 단순히 node:16 이미지를 사용하기 위해서 불러냅니다.
    # 이미지에서 실행되는 Step은 컴퓨터에 직접 접근할 수 없습니다.
    container: 
      # 사용하길 원하는 도커 이미지의 이름을 지정할 수 있습니다.
      image: node:16
      # 이미지에 필요한 환경변수도 지정할 수 있습니다.
      # 어떤 환경변수가 필요한지는 이미지의 공식문서에 나와있습니다.
      # env: 
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv
      MONGODB_CLUSTER_ADDRESS: cluster0.hyesnzu.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
